<a href="https://colab.research.google.com/github/amruthavarshinidara/ML_LAB_2026-27/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
list1 = [1,2,3,4,5]
array1 = np.array(list1)
print(array1)

[1 2 3 4 5]


In [35]:
import numpy as np
from statistics import mean, median, mode
array1 = np.array([1,2,3,4,5])
print(array1)

[1 2 3 4 5]


In [36]:


# Central Tendency Measures
print("Mean:", mean(array1))         # Mean
print("Median:", median(array1))     # Median
print("Mode:", mode(array1))         # Mode

# Measures of Dispersion
print("Variance:", np.var(array1))            # Variance (Population)
print("Standard Deviation:", np.std(array1))


Mean: 3
Median: 3
Mode: 1
Variance: 2.0
Standard Deviation: 1.4142135623730951


create a 2D array with 2 rows and columns

In [24]:
import numpy as np
array1 = np.array([[1,2,3,4,],
                  [5,6,7,8]])
print(array1)


[[1 2 3 4]
 [5 6 7 8]]


In [25]:
# Central Tendency Measures
print("Mean:", mean(list1))         # Mean
print("Median:", median(list1))     # Median
print("Mode:", mode(list1))         # Mode

# Measures of Dispersion
print("Variance:", np.var(list1))            # Variance (Population)
print("Standard Deviation:", np.std(list1))

Mean: 3
Median: 3
Mode: 1
Variance: 2.0
Standard Deviation: 1.4142135623730951


create a 3D numpy array


In [10]:
array1 = np.array([[[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]],

                [[13, 14, 15, 16],
                 [17, 18, 19, 20],
                 [21, 22, 23, 24]]])

print(array1)


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [30]:
# Central Tendency Measures
print("Mean:", mean(list1))         # Mean
print("Median:", median(list1))     # Median
print("Mode:", mode(list1))         # Mode

# Measures of Dispersion
print("Variance:", np.var(list1))            # Variance (Population)
print("Standard Deviation:", np.std(list1))

Mean: 10.833333333333334
Median: 3.5
Mode: 1
Variance: 308.4722222222222
Standard Deviation: 17.563377301140637


In [31]:
array1 = np.array([10,20,30,40])
print(array1.dtype)

int64


In [32]:
print(array1.ndim)

1


In [33]:
print(array1.size)

4


In [37]:
import numpy as np

my_array = np.array([1,2,3,4])

# Print `my_array` before appending
print("my_array before appending:", my_array)

# Append a 1D array to `my_array`
new_array = np.append(my_array, [7, 8, 9, 10])

# Print `new_array`
print("new_array:", new_array)

# Print `my_array` after appending
print("my_array after appending:", my_array)

my_array before appending: [1 2 3 4]
new_array: [ 1  2  3  4  7  8  9 10]
my_array after appending: [1 2 3 4]
